#!/bin/sh

#programme pour changer son DNS local
#
#Usage: ./swipedns.sh [ADDR1] [ADDR2]
#[ADDR1]: Première adresse IP alternative
#[ADDR2]: Deuxième adresse IP alternative
#
#Le mieux pour pouvoir choisir les adresses IP en question est de passer par les serveurs OpenNic
#disponibles à cette adresse: https://www.opennicproject.org/
#
#

current_user=`whoami`

if [ $current_user != "root"  ]; then
    echo "Veuillez executer ce script en tant que root"
    exit 1
fi

echo "# Generated by Connection Manager
nameserver $1
nameserver $2" > /etc/resolv.conf

/etc/init.d/networking restart

if [ $? -ne 0  ]; then
    echo "La commande de relance du service reseau a echoue, veuillez executer manuellement la commande
    /etc/init.d/networking restart
    "
else
    echo "Adresse IP des DNS changee avec succes!"
fi




